config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

get 'home/about' => 'home#about'
devise_for :users, controllers: {
        registrations: 'users/registrations'
}

resources :users

resources :books












  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :books, dependent: :destroy
         attachment :profile_image

         validates :introduction, length: { maximum: 50 }
         validates :name, length: { in: 2..20 }
         validates :name, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

def index
@book = Book.new
@users = User.all
@user = current_user
@books = @user.books.page(params[:page]).reverse_order
end

def show
@book = Book.new
@user = User.find(params[:id])
end

def new

end

def create
@user = User.new(user_params)
   if @user.save
      redirect_to user_path(@user.id)
       else
       @user = User.find(params[:id])
       render action: :edit
    end
end

def edit
@user = User.find(params[:id])
if current_user != @user
	redirect_to user_path(current_user)
end
end

def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render action: :edit
end
end

def destroy
end
private
def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="mx-auto" style="width: 200px;">

<h2 class="form-header-title">User info</h2>
<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
<h3>errorが<%= @user.errors.count %>件あります</h3>
  <ul>
   <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>

 <%= attachment_image_tag @user, :profile_image, size: "100x100",  class: "img-circle pull-left profile-thumb", fallback: "no_images.jpg"%>
     <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
     <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>

     <%= f.label :Name %><br />
          <%= f.text_area :name, autofocus: true %>

<%= f.label :introduction %><br />
    <%= f.text_area :introduction, autofocus: true %>

  <%= f.submit "Update user" %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-lg-3">

<h2>User info</h2>

<%= attachment_image_tag @user, :profile_image, style: "width:100px; height:100px;", format: 'jpg',fallback: "no_images.jpg" %>

　<p>name  <%= @user.name %></p>

  <p>introduction  <%= @user.introduction %></p>

<%= link_to edit_user_path(@user), class: "btn btn-default form-control" do %>
    <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
    <% end %>

<h2>New book</h2>

<%= form_for(@book) do |f| %>

<% if @book.errors.any? %>
<h3>errorが<%= @book.errors.count %>件あります</h3>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</div>

<div class="col-lg-9">
<h2>Users</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
   <tbody>
    <% @users.each do |user| %>
    <tr>
     <td>
      <%= link_to user_path(user.id) do %>
      <%= attachment_image_tag user, :profile_image, style: "width:40px; height:40px;", format: 'jpg',fallback: "no_images.jpg" %>
        <% end %>
      </td>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= link_to "Show", user_path(@user) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>

<div class="container">
<div class="row">
<div class="col-lg-3">

<h2>User info</h2>

<%= attachment_image_tag @user, :profile_image, style: "width:100px; height:100px;", format: 'jpg',fallback: "no_images.jpg" %>

　<p>name  <%= @user.name %></p>

  <p>introduction  <%= @user.introduction %></p>

  <%= link_to edit_user_path(@user), class: "btn btn-default form-control " do %>
    <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
    <% end %>

<h2>New book</h2>

<%= form_for(@book) do |f| %>

<% if @book.errors.any? %>
<h3>errorが<%= @book.errors.count %>件あります</h3>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</div>

<div class="col-lg-9">
<h2>Books</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Opinion</th>
                </tr>
            </thead>
            <tbody>
            <% @user.books.each do |book| %>
             <tr>
             <td>
             <%= link_to book_path(book.id) do %>
             <%= attachment_image_tag @user, :profile_image, style: "width:40px; height:40px;", format: 'jpg',fallback: "no_images.jpg" %>
             <% end %>
             </td>
              <td><%= link_to  book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>