config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

get 'home/about' => 'home#about'
devise_for :users, controllers: {
        registrations: 'users/registrations'
}

resources :users

resources :books












  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

<nav class="navbar navbar-light" style="background-color:#000000;">
  <a class="navbar-brand">Bookers</a>
  <div id="gnavi" class="collapse navbar-collapse navbar-right">
  <div class="container-fluid">
　　<div class="navbar-header">

  <% if user_signed_in? %>

<span class="glyphicon glyphicon-home" aria-hidden="true">
<%= link_to "Home", user_path(current_user) %></span>

<span class="glyphicon glyphicon-user" aria-hidden="true">
<%= link_to "Users", users_path %></span>

<span class="glyphicon glyphicon-book" aria-hidden="true">
<%= link_to "Books", books_path %></span>

<span class="glyphicon glyphicon-log-out" aria-hidden="true">
<%= link_to "logout", destroy_user_session_path, method: :delete  %></span>

<% else %>

<span class="glyphicon glyphicon-home" aria-hidden="true">
<%= link_to "Home", root_path %></span>

<span class="glyphicon glyphicon-link" aria-hidden="true">
<%= link_to "About", home_about_path %></span>

<span class="glyphicon glyphicon-edit" aria-hidden="true">
<%= link_to "sign up", new_user_registration_path %></span>

<span class="glyphicon glyphicon-log-in" aria-hidden="true">
<%= link_to "login", new_user_session_path %></span>


<% end %>
</div>
</div>
</div>
</nav>

  <%= yield %>

 <footer>
  <div class="text-right">
  <p>CopyRight Infratop.inc</p>
</div>
</footer>

</body>
</html>